### ISSUE TITLE
Budgets

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1189]
# Budgets 
Integrate into Consul the work done regarding Participatory Budgets in [Madrid's fork](https://github.com/AyuntamientoMadrid/consul).

In addition to the basic integration we have updated the database structure to take into account multiple budgets. And a more flexible structure with multiple groups (for example lines of action: health, education and employment) and multiple headings within those groups each with its own allocated money (for example districts within a city).

In Madrid the basic structure is 2 groups (city and districts) and within the district's group there are multiple headings, one for each district with their allocated money. But any combination of groups and headings can be created.

### Accepting
  - [x] Change phase names to:
    - [x] Presentación de proyectos
    - [x] Revisión interna de proyectos
    - [x] Fase de apoyos
    - [x] Evaluación de proyectos
    - [x] Votación final
    - [x] Votación finalizada
    - [x] Resultados
  - [x] In the admin section with lots of headings the styling gets displaced (PR #1499)
  - [x] Add admin stats to see how many projects have been created (PR #1500)
  - [x] Increase budget name length to 50 in database (PR #1503)
  - [ ] Add suggest when creating projects (Issue #1354)
  - [ ] Display error message if budget name exceeds maximum length
  - [ ] Admins should be able to delete groups and headings if they are empty
  - [ ] Think about admins having to insert data before it is public (maybe extra setting) 
  - [ ] Display official position badge following the same rules as for proposals 
  
### Selecting
  - [x] Add permissions to support only in one heading  
  - [x] Display tag categories in sidebar
  - [x] Display link to 'unselected feasible projects'
  - [ ] Add admin stats (Done in Madrid's fork PR https://github.com/AyuntamientoMadrid/consul/pull/707)
  - [ ] budgets/1/investments should redirect to budget's show if there is no heading in params 
  - [ ] Show check mark in the heading you have selected

### Valuating  
  - [x] Add cut-off mark functionality
  - [x] Do not display support button for projects
  - [x] In the valuating a proposal form change "data private" for "data not public" (PR #1499)
  - [x] Only allow valuators to finish report if the appropriate fields have been filled out
  - [x] Display number of supports in user facing investments index and show
  - [ ] As a valuator, redirect to budgets/1/budget_investments if there is only one budget
  - [ ] Allow admins to delete valuators 
  - [ ] Restructure filters in the admin investment's index
  - [ ] In admin/valuation investment's index, scope tags to current budget
  - [ ] After valuating a proposal redirect to budgets instead of spending proposals
  - [ ] In admin budget investment's index change filter name "feasible" for "finished feasible"
  - [ ] In admin budgets investments's index display number of supports for each project
  - [ ] Change filter feasible for dropdown (feasible and unfeasible)

### Balloting
  - [x] In investments's show change 'Supports' for 'Votes'
  - [x] When scrolling down, the money bar at the top, needs a little bottom padding
  - [x] In the message 'you have votes in another heading', heading is not readable (color contrast)   
  - [x] Add tag categories in sidebar
  - [x] Make sure we can support and ballot in different headings
  - [x] On investments/_header there is a link with params 'heading' instead of 'heading_id' (PR #1517)
  - [x] Review voting policy is working
  - [x] In review my votes, make sum of money work
  - [x] Add DB constraint to avoid duplicate votes
  - [x] In the money bar, add contrast to the money amount
  - [x] In review my ballot, maintain order of groups when removing investments (PR #1526)
  - [x] In review my ballot, display correct heading name after changing voted heading (PR #1525)
  - [x] In review my ballot, add link to encourage voting in the rest of the groups (PR #1529)
  - [x] Fix back link after removing an investment from 'Check my ballot' (PR https://github.com/consul/consul/pull/1524)
  - [x] In review my ballot make heading info into a link to keep voting (PR #1530)
  - [x] Only display links to unfeasible and unselected proposals in this phase (PR #1532)
  - [x] Update button text to 'Vote' and 'Remove vote' (PR #1534)
  - [x] Email for authors of investment projects that have been selected (PR https://github.com/consul/consul/pull/1536)
  - [x] Email for authors of investment projects that have not been selected (PR https://github.com/consul/consul/pull/1536)
  - [x] Show/hide sidebar votes info depending on selected heading (PR #1535)
  - [x] If an investment project is reclassified remove it's existent votes (PR https://github.com/consul/consul/pull/1537)
  - [x] Do not display voting button for unselected investments (PR https://github.com/consul/consul/pull/1539)
  - [x] Update link text to unselected investments (PR https://github.com/consul/consul/pull/1540)
  - [x] In investment's index, after adding and removing investments, refresh the other voting buttons
  - [x] When a user doble clicks the vote button a uniqueness validation exception is raised (PR #1546)
  - [x] When a user clicks multiple vote buttons very fast it can raise an insufficient money exception (PR #1546)
  - [x] When a selected investment is marked as inviable remove it's votes (PR https://github.com/consul/consul/pull/1550)
  - [x] Unselected filter should include investments with feasibility:undecided (PR #1549)
  - [x] Add participation stats for admins
  - [ ] The money bar seems to disappear and come back sometimes
  - [ ] Remove scroll after marking an investment as selected
  - [ ] Add an alert informing admins that votes will be removed when reclassifying
  - [ ] Email for voters of a reclassified investment project
  - [ ] Email for authors of a reclassified investment project
  - [ ] Make search aware of current filter (unfeasible, selected, unselected)
  - [ ] In Review my votes, when clicking on the amount left link, redirect to the heading instead of the group if there is only one heading in the group.

### Counting Results
  - [x] Add counter to know how many times an investment has been balloted (PR #1508)
  - [x] In investments index and show do not display buttons to support nor number of votes  

### Finished (Results & Stats)
  - [x] Add results page (PR https://github.com/consul/consul/pull/1555)
  - [ ] Add "Finish" button to admin -> Trigger winner calculation to have cached winners/results page
  - [ ] Stats (gender/district/age) page 
  - [ ] Add social media meta tags for results
  - [ ] Display incompatible investments
  - [ ] Only allow accessing the results url in this phase 

### General
- [x] Models
- [x] Dev seeds
- [x] Admin frontend
- [x] Valuators frontend
- [x] Managers frontend
- [x] Welcome page (for now it is budgets#index + budgets#show)
- [x] Add investments to user's show
- [x] Translate error messages in models
- [x] Visible proposals in the first phase
- [x] Add geolocation to proposals and/or map
- [x] Add tags to investments
- [x] Display appropriate orders, headers, and sidebars in each phase
- [x] Add optional association field when creating projects
- [x] Allow users of any age to create projects (PR #1335)
- [x] Hide spending proposals when setting is false
  - [x] Header menu
  - [x] Managers menu
  - [x] Admin menu
  - [x] Admin global settings
  - [x] Public activity
- [x] When creating a comment it displays error can't be blank (PR #1339)
- [x] Checkpoint we can merge with master here
- [x] In group's show, change "Select a heading" for "Select an option"
- [x] Review my activity (spending proposals, ballot)
- [x] Review back link flow (PR #1343)
  - [x] Budgets 1 -> group -> back_link
  - [x] Create a proposal -> back_link (should not send to form)
- [x] Display link to 'unfeasible projects'
- [x] In budget's show display message to login or verify to create proposals (logged in users see button to create)
- [ ] Search
  - [ ] In the initial phases, it should find all projects except unfeasible projects
  - [ ] From the Balloting phase onwards, it should only find selected projects
- [ ] Make geozones for headings optional
- [ ] In my activity display my ballot (only visible for current_user)
- [ ] Review pending user_specs regarding spending_proposals' activity
- [ ] Complete rake task
- [ ] Review hover authentication messages
- [ ] Share on social networks that I have balloted
- [ ] Remove obsolete SpendingProposals 
- [ ] Add friendly routes
- [ ] Add current budget home
- [ ] Display link to unfeasible investments in all phases
- [ ] Add an admin section to use WYSIWYG for email content
- [ ] Consider creating a more minimalistic index
- [ ] When a user is in a heading's index and clicks on sign in, return the user to that heading(only implemented in Madrid's fork).

### For individual issues
- [ ] Display a map of the project location
- [ ] Search
  - [ ] Allow searching by project id
  - [ ] Adapt search to current budget
- [ ] User should be able to delegate on any user
- [ ] Downloadable proposals in csv or pdf format with selected filters
- [ ] Add photos or documentos to investments
- [ ] Automatic emails to authors: 
  - [x] Investment discarded
  - [ ] Investment goes to next phase or not
  - [ ] Evaluation finished (info about reclassification)
  - [ ] Investment winner or not

### Phases
- [x] Accepting
- [x] Reviewing
- [x] Selecting
- [x] Evaluating
- [x] Balloting
- [x] Counting results
- [x] Finished (Results and Stats)

# Use budgets

To use Budgets in development and production add these settings from the rails console:

`Setting['feature.budgets'] = true`
`Setting['feature.spending_proposals'] = nil`
`Setting['min_age_to_participate'] = 16`

In development to load example data you can also run: `rake db:dev_seed`

**Comment by andreslucena** [comment]
Let me know when we have this merged so I can write the docs ;)

**Comment by voodoorai2000** [comment]
This feature is now in master. With the basics for all phases implemented.
There are still some things to polish, which will be added as small issues with the budget's label.
