### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1496]
We need add some changes to improve SEO of site.

- [x] Check `sitemap_generator` gem is working correctly

- [x] Adds to `robot.txt` some paths to avoid their indexation: (PR #1498)

    - Disallow: /*?*locale=

    - Disallow: /users/

    - Disallow: /comments/

    - Disallow: /*?*order

    - Disallow: /*?*search

- [x] Adds `rel="canonical"` on main sections (PR #1528)

- [x] Adds `nofollow` attribute on external links, also on links to sign_in/sign_up forms (PR #1498)

- [x] Remove headings on footer (PR #1498)
