### ISSUE TITLE
Polls - Admin & Front

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1855]
What we need
==

Refactor a little the flow and admin settings for polls.

🖌 **Detailed mockups are uploaded (and updated) to [invisionapp](https://invis.io/4UDEFT5FZ)** (_last updated 18/09_)

Issues list
==
## Admin 
- [x] Polls: Admin section #1948
- [x] Polls: Admin questions #1949
- [x] Polls: Admin questions images #1950
- [x] Polls: Admin questions videos #1951
- [x] Polls: Admin questions documents #1952

## Front

- [ ] Polls: comments #1953
- [x] Polls: questions #1954
- [x] Polls: design #1955

**Comment by iagirre** [comment]
I'll do the first one, "**Admin polls section**" (_Mockup screen 1_)

**Comment by aitbw** [comment]
I'm gonna handle **Admin questions section**

**Comment by zamuro** [comment]
I'll go with polls' front.

**Comment by decabeza** [comment]
Already done! Pending `Polls: comments` continue on #1953
