### ISSUE TITLE
Annotator Polish

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#776]
We are almost ready to launch Legislation annotations. There are a few things to do still.

Important before launch:
- [x] <del>Nice copy describing the process to annotate.</del>  Merged on #778 :tada:
- [x] <del>Flow to reach the legislation.</del> On [Ayuntamiento de Madrid](https://github.com/AyuntamientoMadrid/participacion) repository we use routes **`/processes`** and **`/processes_ordinance`** to reach the legislation.

Not esencial but needs to be done at some point:
- [x] Do not display permission checkboxes when editing. (done in #780)
- [x] Use referer to redirect to legislation after sign in. (done in #787)
- [ ] Permission specs.
- [ ] User not logged in specs.
- [x] <del>Move annotator js files to a folder.</del> Not needed, only one file was used. Just remove the unneeded ones. (done in #780)

**Comment by decabeza** [comment]
- **Nice copy describing the process to annotate.**

  - Merged on #778 :tada:  

- **Flow to reach the legislation** 

  - On [Ayuntamiento de Madrid](https://github.com/AyuntamientoMadrid/participacion) repository we use routes **`/processes`** and **`/processes_ordinance`** to reach the legislation.

**Comment by voodoorai2000** [comment]
Obsolete
