### ISSUE TITLE
Verification via redeemable code

### ISSUE THREAD

**Issue by kikito** [consul/consul#905]
- [x] Welcome screen: Switch link and button (make verification prominent) (#916)
- [x] New screen in /cuentasegura with "do you have an account Yes / No". Yes points to `/verification` (#920)
- [x] Add redeemable code to registration screen when answered "No" (via extra param) (#924)
- [x] Add district (geozone) to users (via #908)
- [x] Add redeemable code to /verification/residence (auto-completed with the verification code in login if it exists) (done in the madrid repo)
- [x] Make verification/letter accept both letter codes & redeemable codes (also done in the madrid repo)
